// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const cfg: any = {
  schema: "prisma/schema.prisma",
};

export default defineConfig(cfg);
